steps:
- name: node:18
  entrypoint: npm
  args: [install]
- name: node:18
  entrypoint: npx
  args: [hardhat, compile]
- name: ubuntu:20.04
  entrypoint: bash
  args:
  - -c
  - |
    apt-get update
    apt-get install -y python3 python3-pip
    pip3 install slither-analyzer
    echo "Slither installed successfully"
    slither --version
    echo "Running Slither analysis on contracts..."
    slither contracts/ --exclude-dependencies || echo "Slither analysis completed"
timeout: 1800s
options:
  logging: CLOUD_LOGGING_ONLY
