steps:
- name: node:18
  entrypoint: npm
  args: [install]
- name: node:18
  entrypoint: npx
  args: [hardhat, compile]
- name: trailofbits/eth-security-toolbox
  entrypoint: slither
  args: [., --json, /workspace/security-report.json]
timeout: 1200s
options:
  logging: CLOUD_LOGGING_ONLY
artifacts:
  objects:
    location: gs://obsk-landing-page-469120_cloudbuild/audit-reports/$BUILD_ID
    paths: ['security-report.json']
