steps:
- name: node:18
  entrypoint: npm
  args: [install]
- name: node:18
  entrypoint: npx
  args: [hardhat, compile]
- name: node:18
  entrypoint: npx
  args: [hardhat, test]
- name: python:3.9
  entrypoint: bash
  args:
  - -c
  - |
    pip install slither-analyzer
    slither contracts/ --exclude-dependencies || echo "Slither analysis completed"
timeout: 1800s
options:
  logging: CLOUD_LOGGING_ONLY
