steps:
- name: node:18
  entrypoint: npm
  args: [install]
- name: node:18
  entrypoint: npx
  args: [hardhat, compile]
- name: python:3.9
  entrypoint: bash
  args:
  - -c
  - |
    pip install slither-analyzer
    slither contracts/ --json /workspace/obsk-security-report.json || echo "Slither analysis completed with findings"
timeout: 1200s
options:
  logging: CLOUD_LOGGING_ONLY
artifacts:
  objects:
    location: gs://obsk-audit-reports-$(date +%Y%m%d)/$BUILD_ID
    paths: ['obsk-security-report.json']
